interval-in-second: 10
messages:
  - "&eLe saviez-vous ? &5&lHall&d&lOf&5&lGames &7s'appelais &c&lCity&d&lOf&6&lMine &7à ces débuts"
  - "&eLe saviez-vous ? &3&lDouglas &7est un chien de garde custom développé avec le &c&lcul"
  - "&eLe saviez-vous ? &7Le &6&lcoronavirus &7est une hallucination &b&lcollective"
  - "&eLe saviez-vous ? &7Le &6&lGouvernement &1Fra&fnç&cais &7nous &c&lmanipule &7comme des moutons"
  - "&eLe saviez-vous ? &7Les &c&ladmins &7du serveur ne sont pas &6&lpayés"
  - "&eLe saviez-vous ? &c&lCity&d&lOf&6&lMine &7était un serveur &a&lRP &7à ses débuts"
  - "&eLe saviez-vous ? &7Le plugin &6&lEssentials &7est détesté par &b&lCapitaineCat0"
  - "&eLe saviez-vous ? &b&lCapitaineCat0 &cne &c&l&npaye pas &cses employés"